In [3]:
import numpy as np

In [4]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [5]:
np.array([1,2,3,4],dtype= 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.random((3,3))

array([[0.71271947, 0.23628663, 0.1458793 ],
       [0.09133778, 0.84222308, 0.07622319],
       [0.91291742, 0.85297408, 0.38087911]])

In [12]:
np.random.normal(0,1,(3,3))

array([[-2.23895046,  1.73960624, -1.0598029 ],
       [-1.11075826,  0.96011023,  1.32501802],
       [ 0.05986524, -0.17225118, -0.70308138]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.empty(3)

array([1., 1., 1.])

In [15]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [18]:
y = np.array([[99], [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [19]:
x = [1,2,3,99.99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])

In [20]:
print(x1)

[1. 2. 3.]


In [21]:
print(x2)

[99.99  3.  ]


In [22]:
print(x3)

[2. 1.]


In [23]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
upper,lower = np.vsplit(grid, [2])

In [25]:
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [26]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [27]:
left, right = np.hsplit(grid,[2])

In [28]:
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [29]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [30]:
x = np.arange(4)
print("x        =",x)
print("x  + 5   =",x)
print("x  - 5   =",x)
print("x  * 2   =",x)

x        = [0 1 2 3]
x  + 5   = [0 1 2 3]
x  - 5   = [0 1 2 3]
x  * 2   = [0 1 2 3]


In [31]:
print("x/2 = ", x/2)
print("x//2 = ", x//2)

x/2 =  [0.  0.5 1.  1.5]
x//2 =  [0 0 1 1]


In [32]:
print("-x    = ",-x)
print(" x ** 2 = ", x**2)
print("x % 2 = ", x % 2)

-x    =  [ 0 -1 -2 -3]
 x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [33]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [34]:
x = np.array([3 - 4j, 4 -3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [35]:
# Trignometric Operations

theta = np.linspace(0, np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [36]:
print("theta            = ",theta)
print("sin(theta)       = ",np.sin(theta))
print("cos(theta)       = ",np.cos(theta))
print("tan(theta)       = ",np.tan(theta))


theta            =  [0.         1.57079633 3.14159265]
sin(theta)       =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)       =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)       =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [37]:
x = [-1,0,1]
print("x       = ",x)
print("arcsin(x)   = ",np.arcsin(x))
print("arccos(x)   = ",np.arccos(x))
print("arctan(x)   = ",np.arctan(x))

x       =  [-1, 0, 1]
arcsin(x)   =  [-1.57079633  0.          1.57079633]
arccos(x)   =  [3.14159265 1.57079633 0.        ]
arctan(x)   =  [-0.78539816  0.          0.78539816]


In [38]:
# Exponents and Logarithms

x = [1,2,3]
print("x     =",x)
print("e^x   =",np.exp(x))
print("2^x   =",np.exp2(x))
print("3^x   =",np.power(3,x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [39]:
x = [1,2,4,10]
print("x         =",x)
print("ln(x)     =",np.log(x))
print("log2(x)   =",np.log2(x))
print("log10(x)  =",np.log10(x))

x         = [1, 2, 4, 10]
ln(x)     = [0.         0.69314718 1.38629436 2.30258509]
log2(x)   = [0.         1.         2.         3.32192809]
log10(x)  = [0.         0.30103    0.60205999 1.        ]


In [40]:
x = [0, 0.001, 0.01,0.1]
print("exp(x) - 1 = ",np.expm1(x))
print("log(1 + x) = ",np.log1p(x))

exp(x) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) =  [0.         0.0009995  0.00995033 0.09531018]


In [41]:
# Specialized Ufuncs

from scipy import special

# Gamma functions (generalized factorials) and related functions

x = [1,5,10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x,2)    =", special.beta(x,2))


gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x,2)    = [0.5        0.03333333 0.00909091]


In [42]:
# Error function (integral of Gaussian)
# Its complement and its inverse.

x = np.array([0,0.3,0.7,1.0])
print("erf(x)   =",special.erf(x))
print("erfc(x)   =",special.erfc(x))
print("erfinv(x)   =",special.erfinv(x))

erf(x)   = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)   = [0.         0.27246271 0.73286908        inf]


In [46]:
#Aggregation

x = np.arange(1,6)
np.add.reduce(x)


15

In [45]:
x = np.arange(1,6)
np.multiply.reduce(x)


120

In [47]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [48]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [49]:
# Outer Product

x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [50]:
# Sum, min, max

L = np.random.random(100)
sum(L)

52.02948797746032

In [51]:
np.sum(L)

52.02948797746032

In [52]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)


115 ms ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [53]:
%timeit np.sum(big_array)

1.04 ms ± 65.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
%timeit min(big_array)

69.8 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
%timeit np.min(big_array)

515 µs ± 51.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
#Exercise
#Sum

M =  np.arange(1,13).reshape((3,4))
print(M)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
np.sum(M)

78

In [72]:
y = np.ndarray.sum(M)   # Sum
print(y)

78


In [66]:
Y = np.add.reduce(M)
print(Y)

[15 18 21 24]


In [70]:
y = np.ndarray.sum(M,axis = 0)   # Column-Wise
print(y)

[15 18 21 24]


In [73]:
y = np.ndarray.sum(M,axis = 1)   # Row-Wise
print(y)

[10 26 42]


In [74]:
#Exercise
#Min
M =  np.arange(1,13).reshape((3,4))
print(M)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [77]:
np.min(M)

1

In [78]:
np.max(M)

12

In [79]:
y = np.ndarray.min(M,axis = 0)   # Column-Wise-Min
print(y)

[1 2 3 4]


In [80]:
y = np.ndarray.max(M,axis = 0)   # Column-Wise-Max
print(y)

[ 9 10 11 12]


In [81]:
y = np.ndarray.min(M,axis = 1)   # Row-Wise-Min
print(y)

[1 5 9]


In [82]:
y = np.ndarray.max(M,axis = 1)   # Row-Wise-Max
print(y)

[ 4  8 12]
